language: node_js
node_js:
  - 12
  - 10

cache: npm

# skip version branches (ie. v1.1.1)
branches:
  except:
    - '/^v\d+\.\d+\.\d+$/'

# install deps
install:
  - npm install

jobs:
  include:
    # test and lint in paralell
    - stage: 'Test'
      script: npm run test
      script: npm run lint
    # report coverage
    - stage: 'Report Test Coverage'
      script: npm run codecov
    # build src
    - stage: 'Build'
      script: npm run build
    # run release branch if we are on master
    - stage: 'Release to npm'
      if: branch == master && !fork
      node_js: 12
      script: npx semantic-release
