name: Publish Package to npmjs
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: 'Test, lint, and build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '18.x'
      - run: npm test
      - run: npm run lint
      # - run: npm run codecov
      - run: npm run build
  release:
    name: 'Publish to NPM registry'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm run build
      - run: npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_RXJS_TOKEN }}
